create table if not exists public.password_reset_codes (
  id bigint generated by default as identity primary key,
  student_id text not null,
  code_hash text not null,
  attempts integer not null default 0,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  used_at timestamptz
);

create index if not exists password_reset_codes_student_idx
  on public.password_reset_codes (student_id, created_at desc);

alter table public.password_reset_codes enable row level security;

drop policy if exists "password reset codes can be created" on public.password_reset_codes;
create policy "password reset codes can be created"
  on public.password_reset_codes for insert to anon, authenticated with check (true);

drop policy if exists "password reset codes can be read" on public.password_reset_codes;
create policy "password reset codes can be read"
  on public.password_reset_codes for select to anon, authenticated using (true);

drop policy if exists "password reset codes can be updated" on public.password_reset_codes;
create policy "password reset codes can be updated"
  on public.password_reset_codes for update to anon, authenticated using (true) with check (true);

drop policy if exists "password reset codes can be deleted" on public.password_reset_codes;
create policy "password reset codes can be deleted"
  on public.password_reset_codes for delete to anon, authenticated using (true);
