create table if not exists public.student_id_change_requests (
  id bigint generated by default as identity primary key,
  student_id text not null unique,
  old_university_id text not null,
  new_university_id text not null unique,
  created_at timestamptz not null default now()
);

alter table public.student_id_change_requests enable row level security;

drop policy if exists "students can request id change" on public.student_id_change_requests;
create policy "students can request id change"
  on public.student_id_change_requests for insert
  to anon, authenticated
  with check (true);

drop policy if exists "students can check id change" on public.student_id_change_requests;
create policy "students can check id change"
  on public.student_id_change_requests for select
  to anon, authenticated
  using (true);

drop policy if exists "students can rollback id change" on public.student_id_change_requests;
create policy "students can rollback id change"
  on public.student_id_change_requests for delete
  to anon, authenticated
  using (true);

create index if not exists student_id_change_new_id_idx
  on public.student_id_change_requests (new_university_id);
